### ISSUE TITLE
`backend::test::test_anonymous_erc20_transfer` fails with `response body fails to deserialize`

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#1179]
I got some error when running the tests, but it might not be related to the change of this PR.

```
test backend::test::test_anonymous_erc20_transfer ... FAILED <69.927s>

failures:

---- backend::test::test_anonymous_erc20_transfer stdout ----
Sent funding tx to deployer
xfr: 987 bytes
mint: 971 bytes
freeze: 979 bytes
Sent funding tx to deployer
thread 'backend::test::test_anonymous_erc20_transfer' panicked at 'called `Result::unwrap()` on an `Err` value: Failed { msg: "relayer error: response body fails to deserialize: io error: unexpected end of file" }', wallet/src/backend.rs:995:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: cape_wallet::backend::test::test_anonymous_erc20_transfer::{{closure}}
   4: std::thread::local::LocalKey<T>::with
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: async_io::driver::block_on
   7: std::thread::local::LocalKey<T>::with
   8: std::thread::local::LocalKey<T>::with
   9: async_std::task::builder::Builder::blocking
  10: core::ops::function::FnOnce::call_once
  11: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    backend::test::test_anonymous_erc20_transfer

test result: FAILED. 14 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 69.93s

error: test failed, to rerun pass '-p cape_wallet --lib'
Sending HUP signal to run-geth: 14774
Cleaning up geth node
Removing geth data dir /run/user/1000/cap-ethereum-data-M56icRDG

```

_Originally posted by @philippecamacho in https://github.com/EspressoSystems/cape/issues/1157#issuecomment-1163263361_

**Comment by sveitser** [comment]
The test `backend::test::test_transfer` now fails on 9760b456d263e983263965829f32a2d8c6f27c90 for me with the same error.

**Comment by sveitser** [comment]
This may be fixed by using 2022-07-17 that fixes the llvm bug. Let's see if the error still occurs sporadically after merging #1202 .
